'''
2024-4-13
This script is account the wet days for model simulation, the definition for wet day is large than 1mm day

reference:
https://rmets.onlinelibrary.wiley.com/doi/full/10.1002/joc.6741
'''
import xarray as xr
import numpy as np
import os

# ================ File information ==================
data_pathin  = '/home/sun/data/download_data/AerChemMIP/day_prect/cdocat/'
data_pathout = '/home/sun/data/process/analysis/AerChem/pr10-20/'

data_list    = os.listdir(data_pathin) ; data_list.sort()

# ====================================================

def get_wet_day(prect):
    '''
        precy should be 1-D array with length of 365
    '''
    count_day = 0

    prect = prect * 86400
    
    count_day = np.sum(prect > 1) 
    
#    print(count_day)
    return count_day

def get_wet_day_model(f0, varname, filename):
    # 1. Get the length of the year
    num_year = len(np.unique(f0.time.dt.year)) #; print(num_year)
    years    = np.unique(f0.time.dt.year) #; print(years)

    # 2. lat/lon information
    lat      = f0.lat.data
    lon      = f0.lon.data

    # 3. Claim the array for the wet days in each year
    wet_days = np.zeros((num_year, len(lat), len(lon)))

    # 4. Start calculating
    # 4.1 Get one-year data
    j  =  0
    for yyyy in years:
        #print(yyyy)
        f0_1year = f0.sel(time=f0.time.dt.year.isin([yyyy]))

        prect1   = f0_1year[varname].data * 86400

        threshold = 25

        wet_days[j] = np.sum(np.logical_and(prect1>10, prect1<20), axis=0)

        j += 1

    print(f'Finish calculating the wet days for {filename}')

    # 4.2 Write to ncfile
    # ------------ Write to a ncfile  ------------------
    ncfile  =  xr.Dataset(
            {
                "wet_day":     (["time", "lat", "lon"], wet_days),             
            },
            coords={
                "time": (["time"], years),
                "lat":  (["lat"],  lat),
                "lon":  (["lon"],  lon),
            },
            )

    ncfile.attrs['description'] = 'Created on 2024-4-13. This file generated by cal_AerChemMIP_wet_days_count_240413.py which counts the wet days for each year.'
    #ncfile.attrs['Note']        = 'This pentad averaged precipitation does not includes NorESM'

    ncfile.to_netcdf(data_pathout + filename)



if __name__ == '__main__':
    for file0 in data_list:
        f1 = xr.open_dataset(data_pathin + file0)

        get_wet_day_model(f1, 'pr', file0)
