'''
2024-4-28
This script is to calculate the ISV intensity of the MJJAS 8-70 bandpass-filtered prect

The calculation method:
For each grid: 1. Select out MJJAS series 2. calculate the standard deviation of 8-70 day bandpass result

Note: The time selection should be set, because I want to present period difference here
'''
import numpy as np
import xarray as xr
import os

# ------------- File Information ------------------
data_path = '/home/sun/data/process/model/aerchemmip-postprocess/day_prect_8_20/'
out_path  = '/home/sun/data/process/analysis/AerChem/ISV1/'

file_list = os.listdir(data_path) ; file_list.sort()

# -------------------------------------------------

# ============= Calculation Part ================

for ff in file_list:
    print(f'Now it is dealing with {ff}')
    f1 = xr.open_dataset(data_path + ff)

    # 1. Select MJJAS
    f1_MJJAS = f1.sel(time=f1.time.dt.month.isin([5, 6, 7, 8, 9]))

    # 1.1 Select the period for historical or furture simulation
    if 'historical' in ff:
        time_year = np.linspace(1985, 2014, 2014-1985+1)
    else:
        time_year = np.linspace(2031, 2050, 2050-2031+1)

    f1_MJJAS_period = f1_MJJAS.sel(time=f1_MJJAS.time.dt.year.isin(time_year))

    # 2. Initialize the array
    isv      = np.zeros((len(f1.lat.data), len(f1.lon.data)))

    # 3. calculate ISV intensity for each grid
    for i in range(len(f1.lat.data)):
        for j in range(len(f1.lon.data)):
            isv[i, j] = np.std(f1_MJJAS_period['filter_pr'].data[:, i, j]*86400 - np.average(f1_MJJAS_period['filter_pr'].data[:, i, j]*86400))

    ncfile  =  xr.Dataset(
        {
            "MJJAS_isv":     (["lat", "lon"], isv),     
        },
        coords={
            "lat":  (["lat"],  f1.lat.data),
            "lon":  (["lon"],  f1.lon.data),
        },
        )

    ncfile.attrs['description'] = 'Created on 2024-4-28. This file save the ISV intensity of the 8-70 band-pass precipitation, generated by cal_AerChemMIP_MJJAS_ISV_intensity_240428.py. The ISV intensity is defined as the standard deviation of the filtered precipitation anomalies and the period is 1985-2014 for historical and 2031-2050 for SSP experiment.'


    ncfile.to_netcdf(out_path + ff)